// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXeu7anjIOw0rLhWImo0Sq3YcUTMTJ9SQ',
    appId: '1:139607690703:web:a15c3a81ae54baf4fd96ba',
    messagingSenderId: '139607690703',
    projectId: 'buildingapp-e32fb',
    authDomain: 'buildingapp-e32fb.firebaseapp.com',
    storageBucket: 'buildingapp-e32fb.firebasestorage.app',
    measurementId: 'G-X0PXKN7F36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPv-cBpZclXNTZkgOIzXf7SNTnfl3h7mA',
    appId: '1:139607690703:android:dd2a0e9f1c003883fd96ba',
    messagingSenderId: '139607690703',
    projectId: 'buildingapp-e32fb',
    storageBucket: 'buildingapp-e32fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgRzikPR-nPV2fHLuTvOtPzu9G0PxdpS4',
    appId: '1:139607690703:ios:18917cfea2cce813fd96ba',
    messagingSenderId: '139607690703',
    projectId: 'buildingapp-e32fb',
    storageBucket: 'buildingapp-e32fb.firebasestorage.app',
    iosBundleId: 'com.example.buildcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgRzikPR-nPV2fHLuTvOtPzu9G0PxdpS4',
    appId: '1:139607690703:ios:18917cfea2cce813fd96ba',
    messagingSenderId: '139607690703',
    projectId: 'buildingapp-e32fb',
    storageBucket: 'buildingapp-e32fb.firebasestorage.app',
    iosBundleId: 'com.example.buildcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXeu7anjIOw0rLhWImo0Sq3YcUTMTJ9SQ',
    appId: '1:139607690703:web:66d570803f0e571cfd96ba',
    messagingSenderId: '139607690703',
    projectId: 'buildingapp-e32fb',
    authDomain: 'buildingapp-e32fb.firebaseapp.com',
    storageBucket: 'buildingapp-e32fb.firebasestorage.app',
    measurementId: 'G-18X3RLT29X',
  );
}
